### ISSUE TITLE
Reproducibility of the rotated 2-moons dataset

### ISSUE THREAD

**Issue by KaiHelli** [BaiTheBest/DRAIN#6]
Hi,
I wanted to ask you how you generated the rotated 2-moons dataset. When we looked at your dataset, we saw that besides the 18-degree rotation, some points seem to move slightly in each step. However, most of the dataset stays the same each time. In the graph below, we put the reversed rotations on top of each other and saw that the transparencies don't perfectly add up. 

![image](https://user-images.githubusercontent.com/18419660/232545924-ddc2c39b-3dd8-4bf3-9b2d-dd0d1fcc1a21.png)

Have you added some noise to a small subset of data points at each step?  Could you also elaborate which parameters you used to create the dataset besides the sequence length and the number of domains?

**Comment by BaiTheBest** [comment]
Most of the datasets used in our paper (including 2-Moons) are inherited from https://github.com/anshuln/Training-for-the-Future. Thanks.
