### ISSUE TITLE
Question about modeling code.

### ISSUE THREAD

**Issue by Yoontae6719** [BaiTheBest/DRAIN#8]
In the above code block, I have a hard time understanding why they are categorized as m1, m2, and m3. Could you please explain if possible?

![image](https://github.com/BaiTheBest/DRAIN/assets/87846187/9e4e382b-2ca6-41bc-b12e-086e4bd007d4)

**Comment by BaiTheBest** [comment]
Basically, the LSTM unit first outputs a hidden variable (a vector) and we slice this vector into the parameters for our target MLP. For example, in your screenshot, "m" stands for the weight matrix and "b" stands for the bias term, and 1,2,3 denotes the layer index. BTW, how to slice a vector into MLP's parameters is not unique and we did this way for simplicity.
